const data = {
  name: "Celtics",
  children: [
    {
      name: "Guards",
      children: [
        {
          category: "Guards",
          name: "Kemba Walker",
          value: 10,
          image: "/google_PNG19644.png",
          url: "https://google.com",
        },
        {
          category: "Guards",
          name: "Marcus Smart",
          value: 10,
          image: "/google_PNG19645.png",
          url: "https://about.google",
        },
        {
          category: "Guards",
          name: "Brad Wanamaker",
          value: 10,
          image: "/logo192.png",
          url: "https://reactjs.org",
        },
        {
          category: "Guards",
          name: "Tremont Waters",
          value: 10,
          image: "/logo192.png",
          url: "https://reactjs.org",
        },
        {
          category: "Guards",
          name: "Carsen Edwards",
          value: 10,
          image: "/logo192.png",
          url: "https://reactjs.org",
        },
        {
          category: "Guards",
          name: "Romeo Langford",
          value: 10,
          image: "/logo192.png",
          url: "https://reactjs.org",
        },
      ],
    },
    {
      name: "Forwards",
      children: [
        {
          category: "Forwards",
          name: "Jayson Tatum",
          value: 10,
          image: "/google_PNG19644.png",
          url: "https://google.com",
        },
        {
          category: "Forwards",
          name: "Jaylen Brown",
          value: 10,
          image: "/google_PNG19645.png",
          url: "https://about.google",
        },
        {
          category: "Forwards",
          name: "Gordon Hayward",
          value: 10,
          image: "/logo192.png",
          url: "https://reactjs.org",
        },
        {
          category: "Forwards",
          name: "Grant Williams",
          value: 10,
          image: "/logo192.png",
          url: "https://reactjs.org",
        },
        {
          category: "Forwards",
          name: "Javonte Green",
          value: 10,
          image: "/logo192.png",
          url: "https://reactjs.org",
        },
        {
          category: "Forwards",
          name: "Semi Ojeleye",
          value: 10,
          image: "/logo192.png",
          url: "https://reactjs.org",
        },
        {
          category: "Forwards",
          name: "Vincent Poirier",
          value: 10,
          image: "/logo192.png",
          url: "https://reactjs.org",
        },
      ],
    },
    {
      name: "Centers",
      children: [
        {
          category: "Centers",
          name: "Daniel Theis",
          value: 10,
          image: "/google_PNG19644.png",
          url: "https://google.com",
        },
        {
          category: "Centers",
          name: "Enes Kanter",
          value: 10,
          image: "/google_PNG19645.png",
          url: "https://about.google",
        },
        {
          category: "Centers",
          name: "Robert Williams III",
          value: 10,
          image: "/logo192.png",
          url: "https://reactjs.org",
        },
        {
          category: "Centers",
          name: "Tacko Fall",
          value: 10,
          image: "/logo192.png",
          url: "https://reactjs.org",
        },
      ],
    },
  ],
};
export default data;
